name: CI Pipeline

on:
  push:
    branches:
      - master
      - 'feature/*'  # Aplica en ramas feature
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Usar Ubuntu para ejecutar el flujo de trabajo

    steps:
      # Paso 1: Checkout el código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: |
          pytest  # Cambia esto si usas otro framework de pruebas

      # Paso 5: (Opcional) Desplegar o hacer otras tareas
      - name: Build project
        run: echo "Building project..."
