name: CI de Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ejecutar pruebas
      run: |
        python -m unittest discover
    - name: Generar reporte de pruebas
      run: |
        # Este es un comando de ejemplo, depende de tu herramienta de prueba
        echo "Pruebas completadas. Ver reporte adjunto."